apiVersion: v1
kind: ServiceAccount
metadata:
  name: sglang-router-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sglang-router-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sglang-router-binding
subjects:
- kind: ServiceAccount
  name: sglang-router-sa
roleRef:
  kind: Role
  name: sglang-router-role
  apiGroup: rbac.authorization.k8s.io