services:
  lmcache-server:
    image: lmcache/vllm-openai:latest
    container_name: lmcache-server
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - LMCACHE_LOCAL_CPU=True
      - LMCACHE_MAX_LOCAL_CPU_SIZE=2
    ipc: host
    ports:
      - 18000:8080
      - 6555:6555
    entrypoint: []
    command: >
      python3 -m lmcache.v1.multiprocess.http_server --l1-size-gb 1 --eviction-policy LRU --max-workers 1 --host 0.0.0.0 --port 6555 --http-port 8080
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/healthcheck || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  vllm-serve:
    image: lmcache/vllm-openai:latest
    container_name: vllm-serve
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - VLLM_WSL2_ENABLE_PIN_MEMORY=1
    ipc: host
    ports:
      - 18001:8000
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    command: >
      Qwen/Qwen3-0.6B --gpu-memory-utilization 0.3 --max-model-len 2048 --max-num-seqs 1 --kv-transfer-config '{"kv_connector":"LMCacheMPConnector", "kv_role":"kv_both", "kv_connector_extra_config": {"lmcache.mp.host": "tcp://lmcache-server", "lmcache.mp.port": 6555, "lmcache.mp.mq_timeout": 10, "lmcache.mp.mp_transfer_mode": "engine_driven"}}'
    depends_on:
      - lmcache-server
